# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'liberica' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebase2
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

end
